
@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name":"mateus",
    "email": "mateus5@gmail.com",
    "password": "1234"
}

###

# @name authenticate

POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "mateus4@gmail.com",
    "password": "1234"
}
###

# @name create_question

POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "new question 6",
    "content": "question's content"
}

###

# @name fetch_recent_question

GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name upload_attachment

POST {{baseUrl}}/attachments
Content-Type: multipart/form-data; boundary=boundary 
Authorization: Bearer {{authToken}}

{
  "fileName": "example.png",
  "fileType": "image/png",
  "body": "iVBORw0KGgoAAAANSUhEUgAAA..."
}




